apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
      - image:  langerca/udagram-frontend:latest
        name: udagram-frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
      restartPolicy: Always
